### ISSUE TITLE
Save raw HTML, not Markdown

### ISSUE THREAD

**Issue by bedeoverend** [SimplaElements/simpla-markdown#11]
It's cleaner to save the markdown and then render it on load, but it does mean there's a perf hit, through a few factors:

- Payload size, 42kb w/ markdownit vs 1.2kb w/o markdownit
- Parse time. Just parsing markdownit will take extra time
- Render time. Even if this is fast normally, it will just add up as you combine it with multiple elements / a low end device / other JS scripts competing for time.

The problem here would be that if you're saving HTML, when it comes to editing you'd need to either parse that HTML into Markdown, or save the Markdown and the HTML into Simpla. That would double the text payload size however.

@seaneking thoughts?

**Comment by bedeoverend** [comment]
Probably worth doing some benchmarks on parse and render time to see what practical difference those make.

**Comment by madeleineostoja** [comment]
Thoughts:

- Saving HTML only means you couldn't initialise this element with static content in a `markdown` or `value` property, but that you'd write HTML content inside it instead, which seems to break the contract of 'just give the element its value'

- Not convinced rendering markdown would be a perf hit worth worrying about, especially since  it'd be pretty unlikely to have more than a few markdown elements on a page 

- Payload size and parse hit, fair enough

- Parsing HTML into markdown sounds fragile to me, especially with static content

You could save both, and only load markdown-it if there's no HTML string saved, which covers the first point. Seems kinda fishy though.

**Comment by madeleineostoja** [comment]
Actually strong no on that last idea, request is biggest source of latency so doubling request size in the name of perf is laughable.

**Comment by madeleineostoja** [comment]
Actually thinking more about this, could be okay - if you think of the markdown as the editing interface, rather than the data, then it kind of makes sense. Definitely still not as intuitive or nice as just using markdown strings, but probably a small enough quirk for a minority use-case (static content) to justify a better experience for the majority case (ie: rendering content).

Will do a super quick spike and see if there's a perceptible perf difference

**Comment by madeleineostoja** [comment]
Did a quick spike on this and tbh can't see a noticeable difference on simpla.io, even with basic benchmarking...

**Comment by madeleineostoja** [comment]
Fixed in https://github.com/SimplaElements/simpla-markdown/releases/tag/v0.4.0
